### PR TITLE
346 tls support

### PR DESCRIPTION
**Pull request by jimmykarily**
Fixes [#346](https://github.com/kairos-io/kairos/issues/346)

### CODE REVIEW

**Comment by jimmykarily** [comment]
Tests only fail when run with the Earthly target.

I changed qemu to send the serial output to a file. I use `find` inside the earthly container to find the state dir (which I print before the tests start). Then I `tail` the `serial.log` file in that directory. The result is that the installation finishes but when it reboots, there are failures among which:

```
[  OK  ] Finished cOS system early rootfs setup.
[FAILED] Failed to start kcrypt online mount.
See 'systemctl status kcrypt.service' for details.
```

so something is wrong when trying to decrypt the filesystem.

**Comment by jimmykarily** [comment]
I think I know what the problem might be. Locally I built the `.iso` using code that includes this fix: https://github.com/kairos-io/kairos/pull/836 . Earthly doesn't have an iso around so it uses `BASE_IMAGE=quay.io/kairos/core-opensuse:latest` to build one. This doesn't include the DNS fix, thus booting fails. I should have thought of this earlier :facepalm: 

All we need is an updated BASE_IMAGE with the fix.
```

**Comment by mudler** [comment]
> I think I know what the problem might be. Locally I built the `.iso` using code that includes this fix: [kairos-io/kairos#836](https://github.com/kairos-io/kairos/pull/836) . Earthly doesn't have an iso around so it uses `BASE_IMAGE=quay.io/kairos/core-opensuse:latest` to build one. This doesn't include the DNS fix, thus booting fails. I should have thought of this earlier facepalm
> 
> All we need is an updated BASE_IMAGE with the fix.

Additionally, now opensuse images are split in `opensuse-leap` and `opensuse-tumbleweed`, so the BASE_IMAGE used here is not getting any updates (see https://kairos.io/docs/reference/image_matrix/)

**Comment by jimmykarily** [comment]
I split each test to its own job (with `matrix`). This way, they can run in parallel (provided we have enough workers) and they can be re-tried separately if one fails.

I'm also thinking about running then outside Earthly. The Earthly target is rather simple, just running a script. Hopefully we can run them with KVM enabled when if we manage to enable that on our self-hosted workers. This will reduce the total time by a lot.

**Comment by jimmykarily** [comment]
After splitting the tests in separate jobs the tests went green: https://github.com/kairos-io/kcrypt-challenger/pull/12/commits/1e3efb57cc64e3a05456d171f10d454b25ce1119
I did one more change to run the tests without earthly: https://github.com/kairos-io/kcrypt-challenger/pull/12/commits/27114b8db8472edba5b7c4813899cf482b670662

and tests are still green.

I want to try to run some self hosted runners with KVM enabled and see what change that makes. This can happen on another PR but it will define whether we run inside Earthly or outside. I can split that last commit to a separate PR and experiment there.

**Review by Itxaka — COMMENTED** [review]
I have no idea how this works, codewise looks good to me

**Comment by jimmykarily** [comment]
> I have no idea how this works, codewise looks good to me

Well, the implementation is pretty much these 2 lines: https://github.com/kairos-io/kcrypt-challenger/pull/12/files#diff-94d75f189ea8b05ff1476dce6652e33bf43bdb1fddade2736156f8366b4eb22bR72-R73

The rest is dancing with tests. This feature needs documentation. I created a new issue for this here: https://github.com/kairos-io/kairos/issues/890

**Pull request merged**
